import type { Metadata } from "next";
import Link from "next/link";
import { CTASection } from "@/components/CTASection";
import { processDetails } from "@/lib/content";
import { pageMetadata, breadcrumbSchema, graph, jsonLd, webPageSchema } from "@/lib/seo";
export const metadata: Metadata = pageMetadata({title:"Process",description:"Understand the business, design the right system, build and launch it, then improve it in daily use.",path:"/process"});
export default function ProcessPage(){return <div className="v3-page">
<section className="v3-page-lead" data-material="paper" data-station="Process"><div className="v3-wrap"><p className="v3-kicker">How we work together</p><h1>A clear plan.<br /><em>A working system.</em></h1><p>Start with the business problem. Make the decisions visible. Build something useful, then put it into daily use.</p><Link className="v3-text-link" href="/contact">Discuss your project<span aria-hidden="true">↗</span></Link></div></section>
<section className="v3-section" data-material="instrument" data-station="The route"><div className="v3-wrap"><p className="v3-kicker">From the first conversation to everyday use</p><div className="v3-route">{processDetails.map(step=><article key={step.id}><span className="v3-route__number">{step.index}</span><div><h2>{step.title}</h2><p>{step.summary}</p><p className="v3-small">{step.detail}</p></div><div className="v3-route__outputs"><p className="v3-kicker">What it leaves you with</p><ul>{step.deliverables.map(item=><li key={item}>{item}</li>)}</ul></div></article>)}</div></div></section>
<section className="v3-section" data-material="paper" data-station="The starting point"><div className="v3-wrap v3-editorial-split"><h2>The scope follows<br /><span>the problem.</span></h2><div><p>A new website is a different engagement from a reporting tool or a customer portal. We work out the priorities, responsibilities and technical approach before the build.</p><p>Have a reporting problem and want a smaller first step? Start with the free reporting teardown.</p><Link className="v3-text-link" href="/teardown">What the teardown includes<span aria-hidden="true">↗</span></Link></div></div></section>
<CTASection title="Tell us where the work gets stuck." /><script type="application/ld+json" dangerouslySetInnerHTML={jsonLd(graph(webPageSchema({name:"Process",path:"/process",description:"The Arctos engagement process."}),breadcrumbSchema([{name:"Process",path:"/process"}])))} /></div>;}
